# Generated by Django 3.2.8 on 2023-03-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_recipe_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
