# Generated by Django 3.2.8 on 2023-03-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_alter_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='review',
        ),
    ]
