# Generated by Django 3.2.8 on 2023-03-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_remove_recipe_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='COOK_TIME',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='PREP_TIME',
            new_name='prep_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='SERVINGS',
            new_name='serving',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='TOTAL_TIME',
            new_name='total_time',
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_recipe', to='Recipe.recipe'),
        ),
    ]
