# Generated by Django 3.2.8 on 2023-03-25 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0006_auto_20230325_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='YIELD',
            new_name='Yield',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 21, 16, 7, 614715), null=True),
        ),
    ]
