# Generated by Django 3.2.8 on 2023-03-25 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0008_auto_20230325_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 3, 25), null=True),
        ),
    ]
