# Generated by Django 3.2.8 on 2023-03-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0011_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
