# Generated by Django 3.2.8 on 2023-03-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0015_recipe_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='photos',
        ),
    ]
