# Generated by Django 3.2.8 on 2023-03-25 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0016_remove_recipe_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 3, 25), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 3, 25), null=True),
        ),
    ]
