# Generated by Django 3.2.8 on 2023-03-25 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0017_auto_20230325_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 25), null=True),
        ),
    ]
