# Generated by Django 3.2.8 on 2023-03-26 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0019_alter_recipe_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 26), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 26), null=True),
        ),
    ]
