# Generated by Django 3.2.8 on 2023-03-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0020_auto_20230326_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
