# Generated by Django 3.2.8 on 2023-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0022_remove_recipe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
