# Generated by Django 3.2.8 on 2023-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0023_recipe_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionvalue',
            name='recipe',
        ),
        migrations.AddField(
            model_name='nutritionvalue',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
