# Generated by Django 3.2.8 on 2023-03-27 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0024_auto_20230326_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionvalue',
            options={'verbose_name': 'ارزش غذایی', 'verbose_name_plural': 'ارزش های غذایی'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'دستور پخت', 'verbose_name_plural': 'دستور پخت'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 27), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 27), null=True),
        ),
    ]
